Repository Ashish-khanagwal/Open-source-practice-and-resources, pull requests merged in 2022-10, with the labels that each got.

#32 Machine Learning
  README.md
Labels: hacktoberfest

#29 added terminal commands under backend topic
  README.md
Labels: hacktoberfest

#41 Made a CSS Frameworks category and put in the resources
  README.md
Labels: hacktoberfest

#47 Add index for laravel
  README.md
Labels: hacktoberfest-accepted

#48 Kanika saini patch 2
  README.md
Labels: hacktoberfest-accepted

#49 Add link to colorzilla
  README.md
Labels: hacktoberfest-accepted

#54 Added Go Resources
  README.md
Labels: hacktoberfest-accepted

#58 Added Angular resources in the Frontend section
  README.md
Labels: hacktoberfest-accepted

#62 Added resources for Blockchain development
  README.md
Labels: hacktoberfest-accepted

#70 add course and roadmap for frontend devlopment
  README.md
Labels: hacktoberfest-accepted

#73 Added DSA resources links
  DSAresources.md
  README.md
Labels: enhancement

#75 Spanish Translation
  ES(Spanish)/README.md
Labels: enhancement

#78 Added Backend Developer roadmap
  README.md
Labels: hacktoberfest-accepted

#79 Added a Python Guide
  README.md
Labels: hacktoberfest-accepted

#83 Added a Css framework documentation and a docker resource
  README.md
Labels: hacktoberfest-accepted

#84 added C++ with STL under DSA Category
  README.md
Labels: hacktoberfest-accepted

#88 Added tag Ruby and resources
  README.md
Labels: hacktoberfest-accepted

#89 Add: added backend resource
  README.md
Labels: hacktoberfest-accepted

#86 ADD: Spanish-resources
  ES(Spanish)/README.md
Labels: enhancement

#93 Added resource for competitive coding and DSA
  README.md
Labels: hacktoberfest-accepted

#97 Added Links for Frontend and API's
  README.md
Labels: hacktoberfest-accepted

#95 French.md
  Translation of readme in French.md
Labels: hacktoberfest-accepted

#104 added video tutorials for spring boot
  README.md
Labels: hacktoberfest-accepted

#103 Add new resources
  README.md
Labels: hacktoberfest-accepted

#109 Added Java Course in Readme.md
  README.md
Labels: hacktoberfest-accepted

#107 Virtualization topic added
  README.md
Labels: hacktoberfest-accepted

#110 Playlist,crash courses and Docs added
  README.md
Labels: hacktoberfest-accepted

#114 added simple and easy git and github tutorial .
  README.md
Labels: hacktoberfest-accepted

#115 Added python video resources in README.md
  README.md
Labels: hacktoberfest-accepted

#117 Added javascript 2022 full course
  README.md
Labels: hacktoberfest-accepted

#118 Added java mooc course
  README.md
Labels: hacktoberfest-accepted

#121 Added flutter resources
  README.md
Labels: hacktoberfest-accepted

#123 Complete crash course via video on git and github in README.md
  README.md
Labels: hacktoberfest-accepted

#125 added some react vdos
  README.md
Labels: hacktoberfest-accepted

#127 Adding video resource in Readme.md
  README.md
Labels: hacktoberfest-accepted

#129 added image classification project in ML
  README.md
Labels: hacktoberfest-accepted

#131 Update README.md
  README.md
Labels: hacktoberfest-accepted

#132 adding foundatio css framework
  README.md
Labels: hacktoberfest-accepted

#133 Added React roadmap doc
  README.md
Labels: hacktoberfest-accepted

#134 Added Next.js Doc and Course
  README.md
Labels: hacktoberfest-accepted

#135 free illustration app
  README.md
Labels: hacktoberfest-accepted

#136 Added GitLab
  README.md
Labels: hacktoberfest-accepted

#137 Update README.md
  README.md
Labels: hacktoberfest-accepted

#138 Update README.md
  README.md
Labels: hacktoberfest-accepted

#139 updated js course list
  README.md
Labels: hacktoberfest-accepted

#140 Update README.md
  README.md
Labels: hacktoberfest-accepted

#142 added fake news detection ML project
  README.md
Labels: hacktoberfest-accepted

#143 Added React redux blogs
  README.md
Labels: hacktoberfest-accepted

#145 JS book recommendation added
  README.md
Labels: hacktoberfest-accepted

#147 added links for django learning
  README.md
Labels: hacktoberfest-accepted

#148 Full stack development curriculum added
  README.md
Labels: hacktoberfest-accepted

#149 DEEP LEARNING
  README.md
Labels: hacktoberfest-accepted

#151 node js learning links
  README.md
Labels: hacktoberfest-accepted

#152 Added Solidity Full Course Tutorials in Blockchain
  README.md
Labels: hacktoberfest-accepted

#153 Core-CS/OS
  README.md
Labels: hacktoberfest-accepted

#154 imp react links for learning
  README.md
Labels: hacktoberfest-accepted
